services:
#  db:
#    image: postgres:16-alpine3.18
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: picservice
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  image-service:
    container_name: image-service
    build:
      context: ..
      dockerfile: .docker/Dockerfile
#    command: bash -c "cd .. && ls"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../src/.dev.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
#      - ..:/app
      - log_volume:/app/log

volumes:
  db_data:
  redis_data:
  log_volume:
