name: deploy picservice workflow
on:
  pull_request:
    branches: ["develop"]
    types: [closed]
jobs:
  tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379

    strategy:
      matrix:
        python-version: ['3.12']

    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_URL: redis://localhost:6379/0
      CELERY_RESULT_EXPIRES: 3600
      SVZ_AVATAR_WIDTH: 200
      SVZ_RECIPE_WIDTH: 768
      BASE_URL: http://127.0.0.1:8000
      MAX_REQUESTS: 10
      TIME_WINDOW: 10
      IP_BLACKLIST_DURATION: 1
      IMAGE_QUALITY: 100
      MAX_IMAGE_HEIGHT: 1080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
        cache: 'pip'

      - name: Start Celery worker in background
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          nohup celery -A src.tasks worker --loglevel=info &

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          mkdir -p src/media/test
          pytest

  build_and_push_to_docker_hub:
    if: github.event.pull_request.merged == true
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/picservice:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/picservice:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/picservice:cache,mode=max
